"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2016-2023, Pulumi Corporation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _PrimitiveType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PrimitiveTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PrimitiveType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TYPE_UNIT: _PrimitiveType.ValueType  # 0
    TYPE_BOOL: _PrimitiveType.ValueType  # 1
    TYPE_BYTE: _PrimitiveType.ValueType  # 2
    TYPE_INT: _PrimitiveType.ValueType  # 3
    TYPE_STRING: _PrimitiveType.ValueType  # 4
    TYPE_PROPERTY_VALUE: _PrimitiveType.ValueType  # 5
    TYPE_DURATION: _PrimitiveType.ValueType  # 6

class PrimitiveType(_PrimitiveType, metaclass=_PrimitiveTypeEnumTypeWrapper): ...

TYPE_UNIT: PrimitiveType.ValueType  # 0
TYPE_BOOL: PrimitiveType.ValueType  # 1
TYPE_BYTE: PrimitiveType.ValueType  # 2
TYPE_INT: PrimitiveType.ValueType  # 3
TYPE_STRING: PrimitiveType.ValueType  # 4
TYPE_PROPERTY_VALUE: PrimitiveType.ValueType  # 5
TYPE_DURATION: PrimitiveType.ValueType  # 6
global___PrimitiveType = PrimitiveType

@typing_extensions.final
class Core(google.protobuf.message.Message):
    """Core is a description of the core interfaces a Pulumi SDK needs to expose. Language SDKs can get hold of
    the most recent version of this by invoking `pulumi core` which will write out a protobuf of this message
    type to stdout.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SDK_FIELD_NUMBER: builtins.int
    @property
    def sdk(self) -> global___SDK: ...
    def __init__(
        self,
        *,
        sdk: global___SDK | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["sdk", b"sdk"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["sdk", b"sdk"]) -> None: ...

global___Core = Core

@typing_extensions.final
class TypeReference(google.protobuf.message.Message):
    """Type is the type of a record field or interface method parameter"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRIMITIVE_FIELD_NUMBER: builtins.int
    ARRAY_FIELD_NUMBER: builtins.int
    MAP_FIELD_NUMBER: builtins.int
    REF_FIELD_NUMBER: builtins.int
    primitive: global___PrimitiveType.ValueType
    @property
    def array(self) -> global___TypeReference: ...
    @property
    def map(self) -> global___TypeReference: ...
    ref: builtins.str
    def __init__(
        self,
        *,
        primitive: global___PrimitiveType.ValueType = ...,
        array: global___TypeReference | None = ...,
        map: global___TypeReference | None = ...,
        ref: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["array", b"array", "element", b"element", "map", b"map", "primitive", b"primitive", "ref", b"ref"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["array", b"array", "element", b"element", "map", b"map", "primitive", b"primitive", "ref", b"ref"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["element", b"element"]) -> typing_extensions.Literal["primitive", "array", "map", "ref"] | None: ...

global___TypeReference = TypeReference

@typing_extensions.final
class EnumerationValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    name: builtins.str
    description: builtins.str
    value: builtins.int
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        description: builtins.str = ...,
        value: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "name", b"name", "value", b"value"]) -> None: ...

global___EnumerationValue = EnumerationValue

@typing_extensions.final
class Enumeration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    VALUES_FIELD_NUMBER: builtins.int
    name: builtins.str
    description: builtins.str
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EnumerationValue]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        description: builtins.str = ...,
        values: collections.abc.Iterable[global___EnumerationValue] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "name", b"name", "values", b"values"]) -> None: ...

global___Enumeration = Enumeration

@typing_extensions.final
class TypeDeclaration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORD_FIELD_NUMBER: builtins.int
    INTERFACE_FIELD_NUMBER: builtins.int
    ENUMERATION_FIELD_NUMBER: builtins.int
    @property
    def record(self) -> global___Record: ...
    @property
    def interface(self) -> global___Interface: ...
    @property
    def enumeration(self) -> global___Enumeration: ...
    def __init__(
        self,
        *,
        record: global___Record | None = ...,
        interface: global___Interface | None = ...,
        enumeration: global___Enumeration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["element", b"element", "enumeration", b"enumeration", "interface", b"interface", "record", b"record"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["element", b"element", "enumeration", b"enumeration", "interface", b"interface", "record", b"record"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["element", b"element"]) -> typing_extensions.Literal["record", "interface", "enumeration"] | None: ...

global___TypeDeclaration = TypeDeclaration

@typing_extensions.final
class Property(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    name: builtins.str
    description: builtins.str
    @property
    def type(self) -> global___TypeReference: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        description: builtins.str = ...,
        type: global___TypeReference | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "name", b"name", "type", b"type"]) -> None: ...

global___Property = Property

@typing_extensions.final
class Record(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    name: builtins.str
    description: builtins.str
    @property
    def properties(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Property]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        description: builtins.str = ...,
        properties: collections.abc.Iterable[global___Property] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "name", b"name", "properties", b"properties"]) -> None: ...

global___Record = Record

@typing_extensions.final
class Parameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    name: builtins.str
    description: builtins.str
    @property
    def type(self) -> global___TypeReference: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        description: builtins.str = ...,
        type: global___TypeReference | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "name", b"name", "type", b"type"]) -> None: ...

global___Parameter = Parameter

@typing_extensions.final
class Method(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    RETURN_TYPE_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    name: builtins.str
    description: builtins.str
    @property
    def return_type(self) -> global___TypeReference: ...
    @property
    def parameters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Parameter]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        description: builtins.str = ...,
        return_type: global___TypeReference | None = ...,
        parameters: collections.abc.Iterable[global___Parameter] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["return_type", b"return_type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "name", b"name", "parameters", b"parameters", "return_type", b"return_type"]) -> None: ...

global___Method = Method

@typing_extensions.final
class Interface(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    METHODS_FIELD_NUMBER: builtins.int
    name: builtins.str
    description: builtins.str
    @property
    def methods(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Method]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        description: builtins.str = ...,
        methods: collections.abc.Iterable[global___Method] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "methods", b"methods", "name", b"name"]) -> None: ...

global___Interface = Interface

@typing_extensions.final
class SDK(google.protobuf.message.Message):
    """SDK is a collection of interfaces that the core SDK should contain."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_DECLARATIONS_FIELD_NUMBER: builtins.int
    @property
    def type_declarations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TypeDeclaration]: ...
    def __init__(
        self,
        *,
        type_declarations: collections.abc.Iterable[global___TypeDeclaration] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["type_declarations", b"type_declarations"]) -> None: ...

global___SDK = SDK
