// Copyright 2016-2023, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "generate"; DO NOT EDIT.

//nolint:lll
package providers

// The severity level of a log message. Errors are fatal; all others are informational.
type LogSeverity int

const (
	// A debug-level message not displayed to end-users (the default).
	Debug LogSeverity = 0
	// An informational message printed to output during resource operations.
	Info LogSeverity = 1
	// A warning to indicate that something went wrong.
	Warning LogSeverity = 2
	// A fatal error indicating that the tool should stop processing subsequent resource operations.
	Error LogSeverity = 3
)
